#!/bin/sh

max_len=25

out=""
status="$(playerctl status)"

[ "$status" = "Playing" ] || [ "$status" = "Paused" ] && {
	out="$(playerctl metadata title)"
	[ ${#out} -gt "$max_len" ] && {
		i="$(( ( $(date +%s) % ( ${#out} + 3 ) ) + 1 ))"
		out="$(echo "$out   $out" | tail -c +$i)"
	}
}

out="$(echo "$out" | head -c "$(( $max_len - 1 ))")"

printf '{"text": %s, "class": %s}\n' \
	"$(echo -n "$out" | jq --raw-input --slurp --ascii-output)" \
	"$(echo -n "$status" | jq --raw-input --slurp --ascii-output)"
