#!/usr/bin/env bash

# TODO: dynamically or based on arguments
mon0="eDP-1"
mon1="HDMI-A-3"

wlr-randr --output "$mon0" --on --pos 0,1080 --output "$mon1" --on --pos 0,0

# Monitors
riverctl map -repeat normal Super+Control K spawn "riverctl focus-output $mon1; echo $mon1 >/tmp/monitor"
riverctl map -repeat normal Super+Control J spawn "riverctl focus-output $mon0; echo $mon0 >/tmp/monitor"
riverctl map -repeat normal Super+Control+Shift K spawn "riverctl send-to-output $mon1; riverctl focus-output $mon1; echo $mon1 >/tmp/monitor"
riverctl map -repeat normal Super+Control+Shift J spawn "riverctl send-to-output $mon0; riverctl focus-output $mon0; echo $mon0 >/tmp/monitor"

# Tags
riverctl map normal Super+Control H       spawn "$XDG_CONFIG_HOME/river/shift_tags - 0 $mon0 $mon1"
riverctl map normal Super+Control L       spawn "$XDG_CONFIG_HOME/river/shift_tags + 0 $mon0 $mon1"
riverctl map normal Super+Control+Shift H spawn "$XDG_CONFIG_HOME/river/shift_tags - 1 $mon0 $mon1"
riverctl map normal Super+Control+Shift L spawn "$XDG_CONFIG_HOME/river/shift_tags + 1 $mon0 $mon1"
for i in $(seq 1 9); do
    tags=$(( 1 << ($i - 1) ))
    riverctl map normal Super $i       spawn "$XDG_CONFIG_HOME/river/shift_tags $tags 0 $mon0 $mon1"
    riverctl map normal Super+Shift $i spawn "$XDG_CONFIG_HOME/river/shift_tags $tags 1 $mon0 $mon1"
done
