#!/bin/sh

# Setup monitor specifics
"$XDG_CONFIG_HOME/river/config_monitors"

# Programs
riverctl map normal Super Return spawn alacritty
riverctl map normal Super W spawn brave
riverctl map normal Super N spawn "$XDG_CONFIG_HOME/river/config_monitors"
riverctl map normal Super+Shift E exit

# Windows
riverctl map normal Super Space zoom
riverctl map normal Super F toggle-float
riverctl map normal Super M toggle-fullscreen
riverctl map normal Super Q close
riverctl map -repeat normal Super J focus-view next
riverctl map -repeat normal Super K focus-view previous
riverctl map -repeat normal Super+Shift J swap next
riverctl map -repeat normal Super+Shift K swap previous
riverctl map -repeat normal Super+Alt H move left 100
riverctl map -repeat normal Super+Alt J move down 100
riverctl map -repeat normal Super+Alt K move up 100
riverctl map -repeat normal Super+Alt L move right 100
riverctl map -repeat normal Super+Alt+Shift H resize horizontal -100
riverctl map -repeat normal Super+Alt+Shift J resize vertical 100
riverctl map -repeat normal Super+Alt+Shift K resize vertical -100
riverctl map -repeat normal Super+Alt+Shift L resize horizontal 100

# Layout
riverctl map -repeat normal Super H       send-layout-cmd rivertile "main-ratio -0.025"
riverctl map -repeat normal Super L       send-layout-cmd rivertile "main-ratio +0.025"
riverctl map -repeat normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map -repeat normal Super+Shift L send-layout-cmd rivertile "main-count -1"
riverctl map -repeat normal Super O       spawn "$XDG_CONFIG_HOME/river/shift_orientation"

# Mouse
riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_RIGHT  resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Function keys
for mode in normal locked; do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "pamixer -i 5"
    riverctl map $mode None XF86AudioLowerVolume  spawn "pamixer -d 5"
    riverctl map $mode None XF86AudioMute         spawn "pamixer --toggle-mute"
    riverctl map $mode None XF86AudioMedia        spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay         spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev         spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext         spawn "playerctl next"
    riverctl map $mode None XF86MonBrightnessUp   spawn "light -A 5"
    riverctl map $mode None XF86MonBrightnessDown spawn "light -U 5"
done

# Colors
riverctl background-color       0x101010
riverctl border-color-focused   0xffffff
riverctl border-color-unfocused 0x303030
riverctl border-color-urgent    0xffff30
riverctl border-width 1

# Keyboard
riverctl hide-cursor when-typing disabled
riverctl keyboard-layout -options caps:escape ie
riverctl set-repeat 30 250

# Stacking
riverctl attach-mode bottom

# Input
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad click-method clickfinger
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad disable-while-typing disabled
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad natural-scroll enabled
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad tap enabled
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad tap-button-map left-right-middle
riverctl input pointer-1739-32402-DELL086F:00_06CB:7E92_Touchpad scroll-method two-finger

# Start layout
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 -main-ratio 0.5 &
