#!/bin/sh

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/delta/$arch"
case "$arch" in
	"x86_64") bin="$dir/delta-0.16.5-x86_64-unknown-linux-musl/delta";   src="https://github.com/dandavison/delta/releases/download/0.16.5/delta-0.16.5-x86_64-unknown-linux-musl.tar.gz";;
	"armv7l") bin="$dir/delta-0.16.5-arm-unknown-linux-gnueabihf/delta"; src="https://github.com/dandavison/delta/releases/download/0.16.5/delta-0.16.5-arm-unknown-linux-gnueabihf.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
