#!/bin/sh

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/eza/$arch"
bin="$dir/eza"
case "$arch" in
	"x86_64") src="https://github.com/eza-community/eza/releases/download/v0.15.2/eza_x86_64-unknown-linux-musl.tar.gz";;
	"armv7l") src="https://github.com/eza-community/eza/releases/download/v0.15.2/eza_arm-unknown-linux-gnueabihf.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
