#!/bin/sh

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/fd/$arch"
case "$arch" in
	"x86_64") bin="$dir/fd-v8.7.0-x86_64-unknown-linux-musl/fd";    src="https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-unknown-linux-musl.tar.gz";;
	"armv71") bin="$dir/fd-v8.7.0-arm-unknown-linux-musleabihf/fd"; src="https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
