#!/bin/sh

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/fzf/$arch"
bin="$dir/fzf"
case "$arch" in
	"x86_64") src="https://github.com/junegunn/fzf/releases/download/0.42.0/fzf-0.42.0-linux_amd64.tar.gz";;
	"armv71") src="https://github.com/junegunn/fzf/releases/download/0.42.0/fzf-0.42.0-linux_armv7.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
