#!/bin/sh

for bin in $(realpath $(which -a fzf)); do
	[ "$(realpath $0)" != "$bin" ] && [ -x "$bin" ] && exec "$bin" "$@"
done

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/fzf/$arch"
bin="$dir/fzf"
case "$arch" in
	"x86_64") src="https://github.com/junegunn/fzf/releases/download/0.42.0/fzf-0.42.0-linux_amd64.tar.gz";;
	"armv7l") src="https://github.com/junegunn/fzf/releases/download/0.42.0/fzf-0.42.0-linux_armv7.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
