#!/bin/sh

for bin in $(realpath $(which -a lf)); do
	[ "$(realpath $0)" != "$bin" ] && [ -x "$bin" ] && exec "$bin" "$@"
done

arch="$(uname --machine)"
dir="$HOME/.local/share/opt/lf/$arch"
bin="$dir/lf"
case "$arch" in
	"x86_64") src="https://github.com/gokcehan/lf/releases/download/r31/lf-linux-amd64.tar.gz";;
	"armv7l") src="https://github.com/gokcehan/lf/releases/download/r31/lf-linux-arm.tar.gz";;
esac

[ -x "$bin" ] || { mkdir -p "$dir" && curl -fL "$src" | tar -xzC "$dir" || exit 1; }
exec "$bin" "$@"
