#!/bin/bash

# Windows
bspc config split_ratio 0.5
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config directional_focus_tightness high

# Pointer
bspc config click_to_focus any
bspc config pointer_modifier mod4
bspc config focus_follows_pointer on

# EWMH
bspc config ignore_ewmh_focus off
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts off
bspc config honor_size_hints on

# Monitors
bspc config remove_disabled_monitors off
bspc config remove_unplugged_monitors off
bspc config merge_overlapping_monitors off
# TODO: autorandr
bspc monitor focused --reset-desktops 1 2 3 4 5 6 7 8 9 0

# Borders
bspc config border_width 1
bspc config normal_border_color "#444444"
bspc config active_border_color "#666666"
bspc config focused_border_color "#cccccc"
bspc config presel_feedback_color "#cccccc"

# Gaps
bspc config window_gap 5
bspc config bottom_padding -5
bspc config left_padding -5
bspc config top_padding -5
bspc config right_padding -5

# Rules
bspc rule --add "*:*:Picture-in-picture" state=floating

# bspc subscribe node_add | while read line; do
	# xdo raise -N "Polybar"
# done &
