#!/bin/bash

bspc config split_ratio 0.5
bspc config directional_focus_tightness low
bspc config click_to_focus any

bspc config border_width 1
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#ffffff"

bspc config window_gap 7
bspc config top_padding -7
bspc config right_padding -7
bspc config bottom_padding -7
bspc config left_padding -7

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc rule --add "*:*:Picture-in-picture" state=floating

bspc subscribe node_add | while read line; do
	xdo raise -N "Polybar"
done &

# work web social games
bspc rule --add "Brave-browser" desktop=2
bspc rule --add "discord" desktop=3
bspc rule --add "Steam" desktop=4
bspc rule --add "PolyMC" desktop=4

displayctrl mobile
