live_config_reload = false

[scrolling]
history = 10000
multiplier = 5

[window]
dynamic_padding = true
opacity = 0.85
dimensions.columns = 120
dimensions.lines = 40

[font]
size = 13.5
normal.family = "Terminess Nerd Font"

[selection]
save_to_clipboard = true

# TODO: keybinding to search username@host
[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Shift|Control"
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"
[[keyboard.bindings]]
action = "ScrollToTop"
key = "A"
mode = "Vi"
mods = "Control"
[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "A"
mode = "Vi"
mods = "Control"
[[keyboard.bindings]]
action = "ScrollToBottom"
key = "A"
mode = "Vi"
mods = "Control"
[[keyboard.bindings]]
action = "Copy"
key = "A"
mode = "Vi"
mods = "Control"
[[keyboard.bindings]]
action = "ClearSelection"
key = "A"
mode = "Vi"
mods = "Control"
[[keyboard.bindings]]
action = "ToggleViMode"
key = "A"
mode = "Vi"
mods = "Control"

[colors]
draw_bold_text_with_bright_colors = true
primary.background = "#000000"
primary.foreground = "#dddddd"
cursor.cursor = "#cccccc"
cursor.text = "#111111"
normal.black = "#000000"
normal.blue = "#0d73cc"
normal.cyan = "#0dcdcd"
normal.green = "#19cb00"
normal.magenta = "#cb1ed1"
normal.red = "#cc0403"
normal.white = "#dddddd"
normal.yellow = "#cecb00"
bright.black = "#767676"
bright.blue = "#1a8fff"
bright.cyan = "#14ffff"
bright.green = "#23fd00"
bright.magenta = "#fd28ff"
bright.red = "#f2201f"
bright.white = "#ffffff"
bright.yellow = "#fffd00"
search.focused_match.background = "#ffffff"
search.focused_match.foreground = "#000000"
search.matches.background = "#edb443"
search.matches.foreground = "#091f2e"
footer_bar.background = "#000000"
footer_bar.foreground = "#ffffff"
line_indicator.background = "#000000"
line_indicator.foreground = "#ffffff"
selection.background = "#fffacd"
selection.text = "#000000"
